---
servers:
- name: pruebaids
  informixserver: prueba
  user: informix
  password: informix
- name: pruebaids2
  informixserver: prueba2
  user: informix
  password: informix
custom: 
- query: select tabid from systables where tabid=99 
  response: tabid

  
